# Generated by Django 4.1.2 on 2023-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_rename_title_schedule_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
