# Generated by Django 4.1.2 on 2023-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_schedule_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
