# Generated by Django 4.1.2 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='flight_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
