# Generated by Django 4.1.2 on 2023-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_schedule_status_alter_schedule_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='estimated_arrival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='estimated_departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
