# Generated by Django 4.1.2 on 2023-02-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=64, unique=True)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departure_time',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.flight'),
        ),
    ]
