# Generated by Django 4.1.2 on 2023-02-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_flight_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
