# Generated by Django 4.1.2 on 2023-02-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ticket_arrival_time_ticket_departure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer',
            new_name='user',
        ),
    ]
