# Generated by Django 4.1.2 on 2023-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_customer_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_arrival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin',
            field=models.CharField(max_length=100),
        ),
    ]
