# Generated by Django 4.1.2 on 2023-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_flight_arrival_time_alter_flight_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
